Feature add new architeture
fga-eps-mds/2023-1-MeasureSoftGram-Doc pull request #120
Opened 2023-06-30 04:34 UTC by DaviMatheus

## Descrição
Mudança e adição do novo repositorio de Parser na arquitetura 

## Tarefas gerais realizadas

- Adição da descriçaõ do serviço
- Mudança no documento de arquitetura
- Adição dos pacotes do Parser

2023-06-30 09:13 UTC, higton approved these changes

2023-07-01 18:31 UTC, GuilhermeBraz requested changes

2023-07-01 18:31 UTC, GuilhermeBraz commented on docs/documentos_de_projeto/arquitetura_do_projeto.md
> +|2.0| 30/06/2023 | Mudança do documetno de arquitetura adicionando o Parser | Davi Matheus, Liverson e Luis |
```suggestion
|2.0| 30/06/2023 | Mudança do documetno de arquitetura adicionando o Parser | Davi Matheus, Liverson e Luis |

```

2023-07-01 18:31 UTC, GuilhermeBraz commented on docs/documentos_de_projeto/arquitetura_do_projeto.md
> +|2.0| 30/06/2023 | Mudança do documetno de arquitetura adicionando o Parser | Davi Matheus, Liverson e Luis |
```suggestion
|2.0| 30/06/2023 | Mudança do documetno de arquitetura adicionando o Parser | Davi Matheus, Liverson e Luis |

```

2023-07-01 18:31 UTC, GuilhermeBraz commented on docs/documentos_de_projeto/arquitetura_do_projeto.md
> +|2.0| 30/06/2023 | Mudança do documetno de arquitetura adicionando o Parser | Davi Matheus, Liverson e Luis |
adicionar enter entre as linhas para arrumar header da introdução

2023-07-01 18:33 UTC, GuilhermeBraz requested changes
adicionar enter entre as linhas para arrumar header da introdução

2023-07-03 13:17 UTC, GuilhermeBraz approved these changes
LGTM

2023-07-03 13:17 UTC, merged