Docs 10 planilha de custos
fga-eps-mds/2023-1-MeasureSoftGram-Doc pull request #19
Opened 2023-05-08 13:14 UTC by luisgfmarques

## Descrição
Foi adicionado o documento de planejamento de custos do projeto, necessitando ainda a inclusão do EVM no documento

## Tarefas gerais realizadas

2023-05-10 12:09 UTC, higton requested changes

2023-05-11 02:38 UTC, luisgfmarques commented on docs/documentos_de_projeto/plano_de_custos.md
> +Considerando que cada membro do grupo irá trabalhar em média 40 horas por mês no projeto, e que o o projeto tem duração de 4 meses e possui 15 membros, é estimado que o custo total no desenvolvimento
e somente um custo aproximado dos desenvolvedores (14,52x40x4x15), sendo somente uma estimativa inicial tendo em vista que o custo "real" vai ficar no EVM

2023-05-11 03:11 UTC, luisgfmarques commented on docs/documentos_de_projeto/plano_de_custos.md
> +
adicionado @higton

2023-05-11 12:06 UTC, higton commented on docs/documentos_de_projeto/plano_de_custos.md
> +
Seria bom adicionar alguns gráficos para a EVM, e adicionar também uma explicação da EVM.

2023-05-11 12:09 UTC, higton commented on docs/documentos_de_projeto/plano_de_custos.md
> +
O que foi adicionado parece ser apenas um sumário, considere adicionar algumas tabelas com mais informações, assim como foi feito nos semestre anteriores.

2023-05-12 22:12 UTC, higton commented on docs/documentos_de_projeto/plano_de_custos.md
> +Considerando que cada membro do grupo irá trabalhar em média 40 horas por mês no projeto, e que o o projeto tem duração de 4 meses e possui 15 membros, é estimado que o custo total no desenvolvimento
Este número está quase 7 vezes maior que o do semestre passado, acho que seria bom descrever melhor.

2023-05-12 23:49 UTC, luisgfmarques commented on docs/documentos_de_projeto/plano_de_custos.md
> +Considerando que cada membro do grupo irá trabalhar em média 40 horas por mês no projeto, e que o o projeto tem duração de 4 meses e possui 15 membros, é estimado que o custo total no desenvolvimento
O custo do semestre passado foi calculado por integrante... enquanto esta documento consta o custo total no desenvolvimento...

2023-05-13 00:14 UTC, luisgfmarques commented on docs/documentos_de_projeto/plano_de_custos.md
> +
adicionado o link para a tabela, onde vai ser realizada a atualização ao decorrer do projeto

2023-05-13 11:44 UTC, higton commented on docs/documentos_de_projeto/plano_de_custos.md
> +
Entendi, acho que não precisa adicionar tudo agora. Podemos adicionar no decorrer do projeto.

2023-05-13 11:47 UTC, higton approved these changes

2023-05-17 22:57 UTC, merged