Guia de contribuição
fga-eps-mds/2023-1-MeasureSoftGram-Doc pull request #9
Opened 2023-04-30 17:33 UTC by CarlosFiuza

## Descrição
Adiciona à wiki o guia de contribuição

## Está consertando alguma issue aberta?
#1 

## Tarefas gerais realizadas
- Tópico "Como contribuir"
- Tópico "Política de Branches"
- Tópico "Política de Commits"
- Tópico "Código de conduta"

2023-05-01 03:04 UTC, luisgfmarques approved these changes
I did not found any errors in these files

2023-05-04 00:23 UTC, higton requested changes

2023-05-04 00:23 UTC, higton commented on docs/guia_contribuicao/commits.md
> +1. O _commits_ deve estar em português e ser sucinto e objetivo, representando claramente o que está sendo alterado naquele _commit_.
Eu acho que não teria problema deixar os commits serem em ingles também.

2023-05-04 00:50 UTC, Jonathan-Oliveira commented on docs/guia_contribuicao/commits.md
> +1. O _commits_ deve estar em português e ser sucinto e objetivo, representando claramente o que está sendo alterado naquele _commit_.
olhando o histórico de política de commits dos outros semetres é em inglês,  irei atualizar para manter a homogenia  entre os semestres

2023-05-05 00:42 UTC, Jonathan-Oliveira commented on docs/guia_contribuicao/commits.md
> +1. O _commits_ deve estar em português e ser sucinto e objetivo, representando claramente o que está sendo alterado naquele _commit_.
padrão alterado para inglês

2023-05-05 14:38 UTC, higton approved these changes

2023-05-06 12:41 UTC, merged